//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StellarisModChecker.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("StellarisModChecker.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LoadMods {
            get {
                return ResourceManager.GetString("LoadMods", resourceCulture);
            }
        }
        
        public static string PlaysetLabel {
            get {
                return ResourceManager.GetString("PlaysetLabel", resourceCulture);
            }
        }
        
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        public static string InstallUpdate {
            get {
                return ResourceManager.GetString("InstallUpdate", resourceCulture);
            }
        }
        
        public static string VerifyAgain {
            get {
                return ResourceManager.GetString("VerifyAgain", resourceCulture);
            }
        }
        
        public static string PlaysetModsHeader {
            get {
                return ResourceManager.GetString("PlaysetModsHeader", resourceCulture);
            }
        }
        
        public static string MissingModsHeader {
            get {
                return ResourceManager.GetString("MissingModsHeader", resourceCulture);
            }
        }
        
        public static string OpenInSteam {
            get {
                return ResourceManager.GetString("OpenInSteam", resourceCulture);
            }
        }
        
        public static string ColPosition {
            get {
                return ResourceManager.GetString("ColPosition", resourceCulture);
            }
        }
        
        public static string ColActive {
            get {
                return ResourceManager.GetString("ColActive", resourceCulture);
            }
        }
        
        public static string ColModName {
            get {
                return ResourceManager.GetString("ColModName", resourceCulture);
            }
        }
        
        public static string ColVersion {
            get {
                return ResourceManager.GetString("ColVersion", resourceCulture);
            }
        }
        
        public static string ColSteamId {
            get {
                return ResourceManager.GetString("ColSteamId", resourceCulture);
            }
        }
        
        public static string ColRequiredBy {
            get {
                return ResourceManager.GetString("ColRequiredBy", resourceCulture);
            }
        }
        
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        public static string SelectedPlaysetFormat {
            get {
                return ResourceManager.GetString("SelectedPlaysetFormat", resourceCulture);
            }
        }
        
        public static string InitError {
            get {
                return ResourceManager.GetString("InitError", resourceCulture);
            }
        }
        
        public static string UpdateChecking {
            get {
                return ResourceManager.GetString("UpdateChecking", resourceCulture);
            }
        }
        
        public static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        public static string UpdateLatest {
            get {
                return ResourceManager.GetString("UpdateLatest", resourceCulture);
            }
        }
        
        public static string UpdateDownloading {
            get {
                return ResourceManager.GetString("UpdateDownloading", resourceCulture);
            }
        }
        
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
